exclude: '[\\/]migrations[\\/]'
repos:
  - repo: https://github.com/timothycrosley/isort
    rev: 4.3.21
    hooks:
      - id: isort
        language_version: python3.8
        additional_dependencies: [toml]

  - repo: https://github.com/psf/black
    rev: 19.10b0
    hooks:
      - id: black
        language_version: python3.8

  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.3
    hooks:
      - id: flake8
        language_version: python3.8
        additional_dependencies:
          - flake8-broken-line
          - flake8-bugbear
          - flake8-builtins
          - flake8-coding
          - flake8-commas
          - flake8-comprehensions
          - flake8-eradicate
          - flake8-quotes
          - pep8-naming
