[tool.black]
line-length = 119
skip-string-normalization = true
target-version = ["py38"]

[tool.isort]
default_section = "THIRDPARTY"
force_grid_wrap = 0
include_trailing_comma = true
known_first_party = ["apps"]
line_length = 119
multi_line_output = 3
use_parentheses = true
